### PR TITLE
Split list into years

### PR DESCRIPTION
**Pull request by msoucy**
This will be better when the list gets longer (like next year)

### CODE REVIEW

**Comment by celskeggs** [comment]
I'd rather wait until we actually have multiple years to handle. As-is, there's already a section heading for 2015. In any case, once we get to 2016 code releases, I'd rather stick 2015 into a new file and 2016 into README.md, so that the main page is always the current year.

**Comment by msoucy** [comment]
In that case, you'd have to rename the readme to a year's name every year, which (among other things) loses git history (a move is treated as a delete and a separate, distinct add). Splitting now is no less accessible, makes it clearer that it (will be) about multiple years, and allows teams to add the current year without the list getting unwieldy immediately.

**Comment by celskeggs** [comment]
I'm well aware of Git's limitations. I don't think that the history of this repository is a high enough priority for that to be a driving issue. If you have a specific reason that the repository's history is highly important, I'd be interested in hearing it.
- Splitting now IS less accessible, because the main README is shown when the main GitHub repository is viewed, and other files are not. (Unless there's a new feature that lets me change the README filename.)
- I think it's clear enough that it's about multiple years given the "2015 season code" heading (though I am open to suggestions if you think the header needs to be more prominent.)
- I don't see how adding to 2015 will be any less unwieldy in a second file than in the main file - the lists are the same length. Once 2016 releases hit, I'll move the contents of README.md to 2015.md (or something), and put a new list into README.md.

I don't want to require people to know that they need to look in a different file - GitHub's interface is not entirely obvious for a number of people.

**Comment by msoucy** [comment]
Doing that will cause problems when people inevitably try to add the current year's releases (as a "look what we're working on now", which one team's already mentioned doing in this file).
I disagree that it's unintuitive to click on a year number, especially when the year list appears above the readme, but since it's your team's repository it is your right to reject this change.

Unfortunately, the header can't be made any larger as it is. (I personally feel that GitHub's display for h1 and h2 are just a bit too similarly-sized, but that can't be helped and it could just be my eyes) As it is, one has to scroll down to actually see that it's specific to 2015.

(As a side note, I'm almost surprised that github doesn't support using a custom default file showed, but supports default branches. Then again, since it supports many capitalization-variations of `README`, `README.txt`, `README.md`, `README.markdown`, `README.rst`, etc, I guess they figured that there was enough choice.)

**Comment by celskeggs** [comment]
I agree that GitHub seems intuitive - it's very intuitive for me! But I've also tried sharing GitHub repositories with people who aren't technically inclined... and they do things like click on the commits instead of the files and ask why the page is pink. (The deletion highlighting.) Or they don't realize that there's a readme on the main page and try clicking in strange places.

I see your point about the current year's releases. However, I don't think this is as important as the list being obvious. This is subject to change, of course, but I'm going to leave it like this for now.

**Pull request closed without merging**
