### PR TITLE
Update readme for Team Xbot 488 code release

### PR DESCRIPTION
**Pull request by JohnGilb**
Adding details about the 2015 Code release for Team Xbot 488

### CODE REVIEW

**Comment by celskeggs** [comment]
Please change `2015 Code` -> `Robot Code on GitHub` and include `on GitHub` for the other GitHub links. This is for consistency with the other entries on the list.

**Comment by JohnGilb** [comment]
@col6y added "... on Github" where appropriate per request. Thanks for the catch.

**Comment by celskeggs** [comment]
Excellent. Thank you!

**Comment by celskeggs** [comment]
@JohnGilb oh, actually, one extra question (I'll edit in the response) - would you classify your code as Java/WPILib, Java/Command-Based, or Java/(something else)?

**Comment by JohnGilb** [comment]
Java/Command-Based

**Comment by celskeggs** [comment]
Fixed in f67e0d5

**Pull request merged**
