### PR TITLE
Add Team 4761

### PR DESCRIPTION
**Pull request by simon-andrews**
Go Rockets! Woo!

### CODE REVIEW

**Comment by celskeggs** [comment]
Would it be possible for your summary message to focus on the interesting aspects of the code, rather than the robot?

**Comment by simon-andrews** [comment]
Done.

**Comment by celskeggs** [comment]
- seperate -> separate
- please move your links into the links section below the summary when they point to separate repositories. Links that go inside one of the linked repositories are fine in the summary.

Thanks!

**Comment by simon-andrews** [comment]
Both fixed.

**Comment by simon-andrews** [comment]
Thanks!

**Pull request merged**
